#!/usr/bin/bash

get_script_dir () {
  SOURCE="${BASH_SOURCE[0]}"
  # While $SOURCE is a symlink, resolve it
  while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$( readlink "$SOURCE" )"
    # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  echo "$DIR"
}
dir_path=$(get_script_dir)


function usage () {
  echo "hetzner-dns-cli"
  echo "Usage:  hetzner-dns-cli [zone|record] [action] [ OPTIONS ]"
  echo ""
  echo "Actions: list create get delete"
  echo ""
  echo "Examples:"
  echo "  - hetzner-dns-cli zone list"
  echo "  - hetzner-dns-cli record list"
  echo ""
  echo "Setting parameters for requests:"
  echo "  - Using command line flags"
  echo "    - hetzner-dns-cli zone create --name your-domain.com"
  echo "    - hetzner-dns-cli record get --zone-id your-zone-id --first-record-only"
  echo "  - Using environment variables:"
  echo "    - NAME=your-domain.com hetzner-dns-cli zone create"
  echo "    - ZONE_ID=your-zone-id FIRST_RECORD_ONLY=1 hetzner-dns-cli zone get"
  echo ""
  echo "Type '--help' after any action to view the help file for that action."
  echo "  - e.g. hetzner-dns-cli zone get --help"
  echo ""
  echo "Typing any invalid hetzner-dns-cli command will display this help file."
  echo ""
}

# save required args (noun and action) for later
noun=$1
action=$2
help=$3

# required args
case $noun in
  zone)
    case $action in
      list)
        if [ "$help" == "help" ]
        then
          SHOW_HELP=1 python3 -m hetzner_dns_cli.zone_list
        else
          python3 -m hetzner_dns_cli.zone_list
        fi
        ;;
      create)
        if [ "$help" == "help" ]
        then
          SHOW_HELP=1 python3 -m hetzner_dns_cli.zone_create
        else
          python3 -m hetzner_dns_cli.zone_create
        fi
        ;;
      get)
        if [ "$help" == "help" ]
        then
          SHOW_HELP=1 python3 -m hetzner_dns_cli.zone_get
        else
          python3 -m hetzner_dns_cli.zone_get
        fi
        ;;
      delete)
        if [ "$help" == "help" ]
        then
          SHOW_HELP=1 python3 -m hetzner_dns_cli.zone_delete
        else
          python3 -m hetzner_dns_cli.zone_delete
        fi
        ;;
      *)
        usage
        ;;
    esac
    ;;
  record)
    case $action in
      list)
        if [ "$help" == "help" ]
        then
          SHOW_HELP=1 python3 -m hetzner_dns_cli.record_list
        else
          python3 -m hetzner_dns_cli.record_list
        fi
        ;;
      create)
        if [ "$help" == "help" ]
        then
          SHOW_HELP=1 python3 -m hetzner_dns_cli.record_create
        else
          python3 -m hetzner_dns_cli.record_create
        fi
        ;;
      get)
        if [ "$help" == "help" ]
        then
          SHOW_HELP=1 python3 -m hetzner_dns_cli.record_get
        else
          python3 -m hetzner_dns_cli.record_get
        fi
        ;;
      delete)
        if [ "$help" == "help" ]
        then
          SHOW_HELP=1 python3 -m hetzner_dns_cli.record_delete
        else
          python3 -m hetzner_dns_cli.record_delete
        fi
        ;;
      *)
        usage
        ;;
    esac
    ;;
  *)
    usage
    ;;
esac
